services:
  - type: worker
    name: amazon-affiliate-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn fastapi_server:app --host 0.0.0.0 --port 5000
    autoDeploy: true
